global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

      
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "jenkins"
    metrics_path: /prometheus/
    scheme: https
    static_configs:
      - targets: ["jenkins.dsp-archiwebf22-eb-we-fh.fr"]

  - job_name: "traefik"
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ["traefik.dsp-archiwebf22-eb-we-fh.fr"]
  
